### PR TITLE
Fix non-existing species access

### LINKED ISSUE #177: Better error message if key doesn't exist due to wrong species config
It was impossible to figure out what's going on for me with the "KeyError" that's thrown when setting species to "yeast" in:

```
import lnschema_bionty as lb

lb.settings.species = "yeast"
```

### PR DESCRIPTION
**Pull request by Zethson**
Fixes #177

### CODE REVIEW

**Comment by Zethson** [comment]
@falexwolf @sunnyosun is it fine if we keep this error message somewhat general or should this only be triggered when setting non-existing species? If it's the latter, I'd specify the error message a bit more and point users to valid values etc.

**Comment by sunnyosun** [comment]
I couldn't reproduce the KeyError somehow...

Screenshot 2023-08-23 at 12 14 17

**Comment by sunnyosun** [comment]
Nevertheless, I think the fix should be here: https://github.com/laminlabs/lnschema-bionty/blob/main/lnschema_bionty/dev/_settings.py#L50

We need to add a check to ensure the species record created from Bionty contains validated species, something along this line:
```
species = lb.Species.from_bionty(name=name)
if species.bionty source is None:
    raise ValueError("species {name} is not found.")
```

**Comment by Zethson** [comment]
Sigh, there's something weird going on again and I run into this error no matter which species I set. Looking into it...

**Comment by Zethson** [comment]
@sunnyosun okay, I was doing weird things because my setup was off. I can confirm that it does what @sunnyosun posted above.

**Pull request closed without merging**
